name: python code test report

on:
  push:
    branches: [ "feature/*" ]
jobs:
  build:
    runs-on : ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: setup env
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
        
      - name: install dependency
        run: |
          pip install pytest pytest-cov

      - name: runs with coverage
        run: |
          pytest --cov=apps --cov-report=term-missing --cov-report=xml --cov-report=html

      - name: Extract branch name
        id: branchName
        run: |
          echo "name=${GITHUB_REF_NAME**/}" >> GITHUB_OUTPUT

        # comment added
      - name: upload report to artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.actor }}-coverage-report-${{ github.run_number }}-${{ github.run_attempt }}
          path: htmlcov

